### ISSUE TITLE
Pluggable classname generator

### ISSUE THREAD

**Issue by cwensel** [UnquietCode/Flapi#197]
We have some very large classnames even if condensed, this causes the quick doc feature in Intellij has a hard time with some of the names.

Hashing the names further in a deterministic way would be a win, but probably out of scope for flapi i would think. would also future proof things if flapi chose to change its naming scheme by default.

**Comment by UnquietCode** [comment]
This implementation satisfies the requirements for #95 as well.

**Comment by UnquietCode** [comment]
A custom name generator can now be provided by calling the `useCustomNameGenerator(...)` method on the fluent builder. The following implementation are provided out of the box:

* `DefaultNameGenerator` - makes no alterations
* `CondensedNameGenerator` - shortens method names
* `TinyNameGenerator` - shortens method and class names
* `HashedNameGenerator` - shortens method and class names using an MD5 hash
