### ISSUE TITLE
JDK8 support

### ISSUE THREAD

**Issue by UnquietCode** [UnquietCode/Flapi#210]
* [x] Move the project to JDK8
* [x] change out the Supplier implementation, check for source version
* [x] ensure 8 is an acceptable version when provided to `Flapi.setJDK`
* [x] ensure travis builds include JDK 8
* [ ] other?

**Comment by cwensel** [comment]
The project being on idk 8 is reasonable, but the runtime if embedded must compile on java 7, and any code generated should compile on 7 as well. a flag for idk 8 or 7 language features might be a compromise

**Comment by UnquietCode** [comment]
Absolutely. This is actually already available through the `Flapi.setJDKVersion(..)` method, where the default is now 7 but all the way down to 5 is supported. Any JDK8 features would only be enabled if the source version were set. In reality, the code generator was never updated beyond Java 6 syntax anyway, but it's nice to make use of newer built-in classes like `Supplier` and `Consumer`.
